version: "3"

services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data
  
  redis:
    image: "redis:3.2-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  app:
    depends_on:
      - "postgres"
      - "redis"
    build: .
    command: bash start
    ports:
      - "3000:3000"
    volumes:
      - box:/box
    env_file:
      - '.env-prod'

  jobs:
    depends_on:
      - "postgres"
      - "redis"
      - "app"
    build: .
    command: bash start_jobs
    volumes:
      - box:/box
    env_file:
      - '.env-prod'
  
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - app
    ports:
      - "80:80"

  box:
    image: "busybox"
    volumes:
      - /box
   
  mailcatcher:
    image: "yappabe/mailcatcher"
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  redis:
  postgres:
  box: