version: "3"

services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data
  
  redis:
    image: "redis:3.2-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
  
  jobs:
    depends_on:
      - "postgres"
      - "redis"
      - "app"
    build: .
    command: bash start_jobs
    volumes:
      - .:/SecretSanta
      - box:/box

  app:
    depends_on:
      - "postgres"
      - "redis"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/SecretSanta
      - box:/box
  
  box:
    image: "busybox"
    volumes:
      - /box
 
volumes:
  redis:
  postgres:
  box: